CREATE TABLE PERSONAS_DISCO (
    ID_PERSONA NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    EDAD NUMBER(3),
    DIA VARCHAR2(50)
);

INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (1,'Juan Perez',25,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (2,'Carlos Ramirez',17,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (3,'Luis Mendoza',30,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (4,'Pedro Gonzalez',15,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (5,'Andres Castro',22,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (6,'Diego Torres',19,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (7,'Jorge Herrera',27,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (8,'Miguel Rojas',16,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (9,'Daniel Vega',24,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (10,'David Molina',21,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (11,'Fernando Silva',28,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (12,'Jose Castillo',14,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (13,'Mario Romero',31,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (14,'Luis Salazar',18,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (15,'Roberto Diaz',35,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (16,'Ricardo Paredes',17,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (17,'Cristian Flores',26,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (18,'Gabriel Lopez',29,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (19,'Alex Vargas',33,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (20,'Kevin Zambrano',15,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (21,'Bryan Cedeño',22,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (22,'Jonathan Mena',24,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (23,'Anthony Reyes',27,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (24,'Sebastian Ortiz',16,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (25,'Esteban Bravo',30,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (26,'Patricio Cabrera',21,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (27,'Hector Guerrero',34,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (28,'Oscar Villacis',13,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (29,'Ivan Benitez',19,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (30,'Marco Aguirre',28,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (31,'Sergio Carrillo',23,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (32,'Pablo Narvaez',17,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (33,'Victor Zamora',31,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (34,'Alberto Bonilla',20,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (35,'Guillermo Paz',36,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (36,'Nicolas Tapia',25,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (37,'Adrian Ponce',26,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (38,'Mauricio Lara',24,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (39,'Felipe Cabrera',32,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (40,'Rafael Calderon',14,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (41,'Javier Acosta',27,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (42,'Bruno Peralta',22,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (43,'Manuel Galvez',29,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (44,'Cristobal Mera',26,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (45,'Leonardo Espinoza',34,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (46,'Rodrigo Montalvo',23,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (47,'Eduardo Ibarra',28,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (48,'Samuel Navas',17,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (49,'Mateo Hidalgo',21,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (50,'Joel Santillan',30,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (51,'Daniel Cordero',25,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (52,'Martin Saavedra',15,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (53,'Emilio Calderon',33,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (54,'Alexis Carrasco',19,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (55,'Julio Andrade',26,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (56,'Cristian Ponce',24,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (57,'Ruben Arevalo',24,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (58,'Mario Cevallos',22,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (59,'Angel Quintero',27,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (60,'Kevin Aguayo',17,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (61,'Esteban Barrera',29,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (62,'Diego Navarrete',16,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (63,'Francisco Yanez',34,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (64,'Julian Pineda',23,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (65,'Pablo Vera',28,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (66,'Ricardo Gallardo',15,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (67,'Fernando Arce',21,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (68,'Brayan Renteria',17,'VIERNES');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (69,'Victor Zambrano',32,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (70,'Adrian Torres',24,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (71,'Adriana Torres',20,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (72,'Adriana Macias',16,'SABADO');
INSERT INTO PERSONAS_DISCO(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (73,'Alison Solis',16,'SABADO');

SELECT * FROM PERSONAS_DISCO;



DECLARE
    CURSOR C_PERSONASDISCO IS
    SELECT NOMBRE, EDAD, DIA
    FROM PERSONAS_DISCO
    WHERE DIA = 'VIERNES';

    V_NOMBRE PERSONAS_DISCO.NOMBRE%TYPE;
    V_EDAD PERSONAS_DISCO.EDAD%TYPE;
    V_DIA PERSONAS_DISCO.DIA%TYPE;

    V_AFORO NUMBER :=0;

BEGIN 
    OPEN C_PERSONASDISCO;
    LOOP
        FETCH C_PERSONASDISCO INTO V_NOMBRE, V_EDAD, V_DIA;
        EXIT WHEN C_PERSONASDISCO%NOTFOUND;
            IF V_EDAD >= 18 THEN
                IF V_AFORO < 50 THEN
                    V_AFORO := V_AFORO + 1;
                        DBMS_OUTPUT.PUT_LINE('ES MAYOR DE EDAD PUEDE INGRESAR A LA DISCO: ' || V_NOMBRE || ' - EDAD: ' || V_EDAD || ' - DIA: ' || V_DIA || ' - AFORO ACTUAL: ' || V_AFORO);
                    ELSE 
                        DBMS_OUTPUT.PUT_LINE('YA NO HAY DISPONIBILIDAD PARA SU INGRESO”');
                    END IF;
            ELSE 
                DBMS_OUTPUT.PUT_LINE('ES MENOR DE EDAD PROHIBIDO INGRESO A LA DISCO: ' || V_NOMBRE || ' - EDAD: ' || V_EDAD);
            END IF;
    END LOOP;

    CLOSE C_PERSONASDISCO;
END;



DECLARE
    CURSOR C_PERSONASDISCO IS
    SELECT NOMBRE, EDAD, DIA
    FROM PERSONAS_DISCO
    WHERE DIA = 'SABADO';

    V_NOMBRE PERSONAS_DISCO.NOMBRE%TYPE;
    V_EDAD PERSONAS_DISCO.EDAD%TYPE;
    V_DIA PERSONAS_DISCO.DIA%TYPE;

    V_AFORO NUMBER :=0;

BEGIN 
    OPEN C_PERSONASDISCO;
    LOOP
        FETCH C_PERSONASDISCO INTO V_NOMBRE, V_EDAD, V_DIA;
        EXIT WHEN C_PERSONASDISCO%NOTFOUND;
            IF V_EDAD >= 18 THEN
                IF V_AFORO < 50 THEN
                    V_AFORO := V_AFORO + 1;
                        DBMS_OUTPUT.PUT_LINE('ES MAYOR DE EDAD PUEDE INGRESAR A LA DISCO: ' || V_NOMBRE || ' - EDAD: ' || V_EDAD || ' - DIA: ' || V_DIA || ' - AFORO ACTUAL: ' || V_AFORO);
                    ELSE 
                        DBMS_OUTPUT.PUT_LINE('ES MAYOR DE EDAD - NOMBRE: ' || V_NOMBRE || ' - YA NO HAY DISPONIBILIDAD PARA SU INGRESO”');
                    END IF;
            ELSE 
                DBMS_OUTPUT.PUT_LINE('ES MENOR DE EDAD PROHIBIDO INGRESO A LA DISCO: ' || V_NOMBRE || ' - EDAD: ' || V_EDAD);
            END IF;
    END LOOP;

    CLOSE C_PERSONASDISCO;
END;