CREATE TABLE PERSONAS (
    ID_PERSONA NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    EDAD NUMBER(3),
    DIA VARCHAR2(50)
);

INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (1,'Juan Perez',25,'SABADO');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (2,'Carlos Ramirez',17,'VIERNES');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (3,'Luis Mendoza',30,'SABADO');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (4,'Pedro Gonzalez',15,'VIERNES');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (5,'Andres Castro',22,'SABADO');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (6,'Diego Torres',19,'SABADO');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (7,'Jorge Herrera',27,'SABADO');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (8,'Miguel Rojas',16,'VIERNES');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (9,'Daniel Vega',24,'SABADO');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (10,'David Molina',21,'SABADO');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (11,'Fernando Silva',28,'SABADO');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (12,'Jose Castillo',14,'VIERNES');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (13,'Mario Romero',31,'SABADO');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (14,'Luis Salazar',18,'SABADO');
INSERT INTO PERSONAS(ID_PERSONA, NOMBRE, EDAD, DIA) VALUES (15,'Roberto Diaz',35,'SABADO');


SELECT * FROM PERSONAS;


--PROCESO O FUNCION 
SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE mostrar_mayores
IS
    CURSOR c_personas IS
        SELECT NOMBRE, EDAD, DIA
        FROM PERSONAS
        WHERE DIA IN ('VIERNES', 'SABADO');

    v_nombre PERSONAS.NOMBRE%TYPE;
    v_edad PERSONAS.EDAD%TYPE;
    v_dia PERSONAS.DIA%TYPE;

BEGIN
    OPEN c_personas;
    LOOP
        FETCH c_personas INTO v_nombre, v_edad, v_dia;
        EXIT WHEN c_personas%NOTFOUND;
        IF v_edad >= 18 THEN
            DBMS_OUTPUT.PUT_LINE('Persona mayor de edad: ' || v_nombre || ' - Edad: ' || v_edad || ' - DIA: ' || v_dia);
        ELSE
            DBMS_OUTPUT.PUT_LINE('Persona menor de edad: ' || v_nombre || ' - Edad: ' || v_edad);
        END IF;
    END LOOP;
    CLOSE c_personas;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Ocurrió un error: ' || SQLERRM);
END;

BEGIN
    mostrar_mayores;
END;





